
name: My First YAML Code

on: [push]

jobs:
  say_hello_job:

    runs-on: ubuntu-latest

    steps:
      -name: Say Hello
      run: echo "Hello World! I am running automatically!"

      -name: Check the system
      run: pwd && ls -la
