name: Second YAML CODE
on: [push]

jobs:
  remove_old_yaml_file:
    runs-on: ubuntu-latest

    steps:
      - name: Present Working
        run: pwd && ls -la
      - name: Delete YAML
        run: rm .github/workflows/hello.yml